volumes:
  postgres_data:
  # Note: for mysql_data
  # database:
  #   driver: local

services:
  postgres:
    image: postgres:latest
    container_name: turborepo_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prismapass
      POSTGRES_DB: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql


  # mysql:
  #   platform: linux/amd64
  #   image: mysql:8.0.32
  #   container_name: turborepo_mysql
  #   restart: always
  #   ports:
  #     - 3306:3306
  #   environment:
  #     MYSQL_DATABASE: turborepo
  #     MYSQL_ALLOW_EMPTY_PASSWORD: 1
  #   volumes:
  #     - database:/var/lib/mysql
  